name: FlutterNews
description: A new Flutter application.

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  url_launcher: ^4.0.2
  share: ^0.6.0+1
  http: ^0.12.0
  bsev: ^0.5.5

dev_dependencies:
  flutter_test:
    sdk: flutter

font_awesome_flutter: ^7.1.0
flutter_staggered_grid_view: "^0.2.2"
cloud_firestore: 0.7.4
firebase_analytics: 1.0.2
firebase_messaging: 1.0.4
carousel_pro: ^0.0.13
transparent_image: 0.1.0
scoped_model: ^0.3.0
path_provider: ^0.4.1
firebase_auth: 0.5.18
url_launcher: ^3.0.3


flutter:

  uses-material-design: true
  assets:
      - assets/place_holder.jpg
      - assets/place_holder_2.jpg
      - assets/place_holder_3.jpg
      - resources/lang/en.json
      - resources/lang/pt.json
